# Environments Configuration
# Base environment settings that can be overridden

environments:
  # Development environment
  development:
    description: "Development and testing environment"
    characteristics:
      - "Relaxed security policies"
      - "Smaller resource allocations"
      - "Frequent deployments"
      - "Debug logging enabled"
    network:
      cidr: "192.168.25.0/24"
      vlan: 25
    features:
      debug_mode: true
      monitoring_retention: "7d"
      backup_retention: "3d"
      auto_scaling: false

  # Staging environment
  staging:
    description: "Pre-production testing environment"
    characteristics:
      - "Production-like configuration"
      - "Moderate resource allocations"
      - "Scheduled deployments"
      - "Standard logging"
    network:
      cidr: "192.168.26.0/24"
      vlan: 26
    features:
      debug_mode: false
      monitoring_retention: "14d"
      backup_retention: "7d"
      auto_scaling: true

  # Production environment
  production:
    description: "Production environment"
    characteristics:
      - "Strict security policies"
      - "Full resource allocations"
      - "Controlled deployments"
      - "Structured logging"
    network:
      cidr: "192.168.16.0/24"
      vlan: 16
    features:
      debug_mode: false
      monitoring_retention: "30d"
      backup_retention: "30d"
      auto_scaling: true
      high_availability: true

  # Common settings across environments
  common:
    timezone: "UTC"
    locale: "en_US.UTF-8"
    ntp_servers:
      - "time.google.com"
      - "time.cloudflare.com"
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"
      - "1.1.1.1"
