# Global Configuration Settings
# Base values shared across all environments and tools

global:
  # Domain Configuration
  domain:
    base: "homelab.local"
    tld: "local"

  # Namespaces
  namespaces:
    core:
      - cert-manager
      - ingress-nginx
      - metallb-system
      - longhorn-system
    applications:
      - gitlab
      - keycloak
      - monitoring
      - ai-ml
    system:
      - kube-system
      - kube-public
      - kube-node-lease

  # Common Labels
  labels:
    app.kubernetes.io/managed-by: "homelab-infra"
    app.kubernetes.io/part-of: "homelab"
    homelab.local/environment: "{{ .Values.environment }}"
    homelab.local/component: "{{ .Values.component }}"

  # Image Registry Settings
  registry:
    default: "docker.io"
    pullPolicy: "IfNotPresent"
    pullSecrets: []

  # Common Annotations
  annotations:
    deployment.kubernetes.io/revision: '{{ .Values.revision | default "1" }}'
    homelab.local/managed-by: "centralized-config"
    homelab.local/last-updated: '{{ now | date "2006-01-02T15:04:05Z" }}'

# Service Discovery
services:
  # Core Infrastructure Services
  cert-manager:
    namespace: cert-manager
    port: 9402

  ingress-nginx:
    namespace: ingress-nginx
    controller:
      port: 80
      secure_port: 443

  metallb:
    namespace: metallb-system
    webhook_port: 9443

  longhorn:
    namespace: longhorn-system
    ui_port: 80
    manager_port: 9500

  # Application Services
  gitlab:
    namespace: gitlab
    port: 80
    ssh_port: 22
    registry_port: 5050

  keycloak:
    namespace: keycloak
    port: 8080
    admin_port: 9990

  monitoring:
    prometheus:
      namespace: monitoring
      port: 9090
    grafana:
      namespace: monitoring
      port: 3000
    alertmanager:
      namespace: monitoring
      port: 9093

# Certificate Management
certificates:
  issuer:
    email: "admin@{{ .Values.global.domain.base }}"
    staging_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    production_server: "https://acme-v02.api.letsencrypt.org/directory"

  # Default certificate settings
  defaults:
    duration: "2160h" # 90 days
    renewBefore: "360h" # 15 days
    algorithm: "RSA"
    size: 2048
