apiVersion: v2
name: storage
description: Storage solutions for homelab k3s cluster with security baseline
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  # Security baseline - inherit from security policies
  - name: security-baseline
    version: "0.1.0"
    repository: "file://../security-baseline"
    condition: security-baseline.enabled

  - name: longhorn
    version: "1.7.1"
    repository: https://charts.longhorn.io
    condition: longhorn.enabled

maintainers:
  - name: Tyler Zervas
    email: tz-dev@vectorweight.com

keywords:
  - storage
  - longhorn
  - persistent-volumes
  - security
