# K3s Server Configuration
# Generated by Terraform

# Cluster networking
%{ if cluster_cidr != "" }cluster-cidr: "${cluster_cidr}"%{ endif }
%{ if service_cidr != "" }service-cidr: "${service_cidr}"%{ endif }
%{ if cluster_dns != "" }cluster-dns: "${cluster_dns}"%{ endif }

# Components to disable
%{ if length(disable_components) > 0 }disable:
%{ for component in disable_components ~}
  - ${component}
%{ endfor ~}
%{ endif }

# Node configuration
%{ if length(node_taints) > 0 }node-taint:
%{ for taint in node_taints ~}
  - "${taint}"
%{ endfor ~}
%{ endif }

%{ if length(node_labels) > 0 }node-label:
%{ for key, value in node_labels ~}
  - "${key}=${value}"
%{ endfor ~}
%{ endif }

# Server configuration
write-kubeconfig-mode: "0644"
log: /var/log/k3s.log

# TLS configuration
tls-san:
  - "127.0.0.1"
  - "localhost"

# Flannel configuration
flannel-backend: "vxlan"

# Data directory
data-dir: "/var/lib/rancher/k3s"

# Additional server arguments
%{ if length(extra_args) > 0 }# Extra arguments: ${join(" ", extra_args)}%{ endif }

# Security settings
protect-kernel-defaults: false

# Disable built-in network policy controller if using external solution
disable-network-policy: false

# Kube API server arguments
kube-apiserver-arg:
  - "enable-admission-plugins=NodeRestriction"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=3"
  - "audit-log-maxsize=100"
  - "audit-log-path=/var/log/k3s-audit.log"

# Kube controller manager arguments
kube-controller-manager-arg:
  - "bind-address=127.0.0.1"
  - "secure-port=10257"

# Kubelet arguments
kubelet-arg:
  - "protect-kernel-defaults=false"
  - "read-only-port=0"
  - "authorization-mode=Webhook"
  - "streaming-connection-idle-timeout=5m"
