apiVersion: v2
name: monitoring
description: Complete monitoring and observability stack for homelab
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  # Security baseline - inherit from security policies
  - name: security-baseline
    version: "0.1.0"
    repository: "file://../security-baseline"
    condition: security-baseline.enabled

  - name: kube-prometheus-stack
    version: "61.7.2"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled

  - name: loki
    version: "6.6.4"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled

  - name: promtail
    version: "6.16.4"
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled

  - name: grafana
    version: "8.4.2"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

maintainers:
  - name: homelab-admin
    email: admin@homelab.local
