[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "homelab-testing-framework"
version = "0.1.0"
description = "Comprehensive testing framework for homelab infrastructure validation"
readme = "scripts/testing/README.md"
license = "MIT"
requires-python = ">=3.8"
authors = [
    {name = "Tyler Zervas", email = "tz-dev@vectorweight.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Systems Administration",
    "Topic :: Software Development :: Testing",
]

dependencies = [
    "kubernetes>=28.0.0",
    "requests>=2.31.0",
    "pyyaml>=6.0.1",
    "jsonschema>=4.19.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
    "pre-commit>=3.3.0",
]

[project.urls]
Homepage = "https://github.com/tzervas/homelab-infra"
Repository = "https://github.com/tzervas/homelab-infra.git"
Issues = "https://github.com/tzervas/homelab-infra/issues"

[project.scripts]
homelab-test = "scripts.testing.test_reporter:main"
homelab-config-validator = "scripts.testing.config_validator:main"
homelab-health = "scripts.testing.infrastructure_health:main"
homelab-service-check = "scripts.testing.service_checker:main"
homelab-security = "scripts.testing.network_security:main"
homelab-integration = "scripts.testing.integration_tester:main"

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py311", "py312"]
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --strict-markers --strict-config"
testpaths = [
    "tests",
    "scripts/testing",
]
python_files = [
    "test_*.py",
    "*_test.py",
]
