# Development Environment Values

global:
  replicas: 1
  resourceQuota: false
  storageClass: "standard"
  environment: "development"
  domain: "dev.homelab.local"  # Development domain

ingress:
  enabled: true
  host: "dev.homelab.local"
  tls: false

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

monitoring:
  enabled: true
  prometheus:
    retention: "7d"
  grafana:
    persistence: false

# Development-specific overrides
debug: true
logLevel: "debug"
