# Sensitive Values Template
# Copy to values-secrets.yaml and fill in actual values
# Never commit values-secrets.yaml to version control

global:
  # Override sensitive domain information
  domain: "${HOMELAB_DOMAIN:-homelab.local}"
  
# GitLab sensitive values
gitlab:
  global:
    # Database passwords
    psql:
      password: "${GITLAB_DB_PASSWORD}"
    
    # Root password for GitLab
    initialRootPassword:
      secret: gitlab-initial-root-password
      key: password
      
    # SMTP configuration
    smtp:
      enabled: true
      address: "${SMTP_SERVER:-smtp.gmail.com}"
      port: 587
      user_name: "${SMTP_USERNAME}"
      password:
        secret: gitlab-smtp-password
        key: password
      domain: "${SMTP_DOMAIN:-gmail.com}"
      authentication: "login"
      starttls_auto: true

# Keycloak sensitive values  
keycloak:
  auth:
    adminUser: admin
    adminPassword: "${KEYCLOAK_ADMIN_PASSWORD}"
    
  postgresql:
    auth:
      postgresPassword: "${KEYCLOAK_DB_PASSWORD}"
      password: "${KEYCLOAK_DB_PASSWORD}"

# Monitoring sensitive values
kube-prometheus-stack:
  grafana:
    adminPassword: "${GRAFANA_ADMIN_PASSWORD}"
    
# TLS Certificate configuration
cert-manager:
  global:
    leaderElection:
      namespace: "cert-manager"
  
  # ACME Challenge configuration
  clusterIssuer:
    email: "${TLS_EMAIL:-admin@homelab.local}"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    
# Ingress authentication
ingress-nginx:
  controller:
    # Basic auth for protected services
    extraArgs:
      default-ssl-certificate: "default/homelab-tls"

# Longhorn backup configuration
longhorn:
  defaultSettings:
    backupTarget: "${LONGHORN_BACKUP_TARGET:-}"
    backupTargetCredentialSecret: "${LONGHORN_BACKUP_SECRET:-}"

# MetalLB IP ranges (environment specific)
metallb:
  configInline:
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - "${METALLB_IP_RANGE:-192.168.16.200-192.168.16.220}"