global:
  domain: "homelab.local"
  environment: "production"
  
  # TLS Configuration
  tls:
    enabled: true
    issuer: "letsencrypt-prod"

  # Production security contexts - strict enforcement
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

  # Pod security standards
  podSecurityStandards:
    enforce: "restricted"
    audit: "restricted"
    warn: "restricted"

# Full resource allocation for production
resources:
  limits:
    cpu: "4000m"
    memory: "8Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"

# MetalLB Configuration for Production
metallb:
  configInline:
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.25.240-192.168.25.250

# Full retention for production
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      retention: "30d"
      retentionSize: "45GB"
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 50Gi
      resources:
        limits:
          cpu: 2000m
          memory: 8Gi
        requests:
          cpu: 500m
          memory: 2Gi

loki:
  singleBinary:
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    persistence:
      size: 20Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 512Mi

grafana:
  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
  persistence:
    size: 10Gi
  adminPassword: "ChangeMeInProduction!"  # Use sealed-secrets for this

# Production Longhorn settings
longhorn:
  defaultSettings:
    defaultReplicaCount: 3  # Triple replication for production
    storageOverProvisioningPercentage: 200
    backupTarget: "s3://longhorn-backups@us-east-1/"  # Configure your backup target

# Full monitoring enabled in production
ingress-nginx:
  controller:
    containerSecurityContext:
      runAsNonRoot: false  # Nginx needs root for port binding
      runAsUser: 101
      runAsGroup: 101
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
          - CHOWN
          - SETGID
          - SETUID
      seccompProfile:
        type: RuntimeDefault
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 256Mi

# Production-specific TLS configuration
cert-manager:
  clusterIssuer:
    production: true
    email: "admin@homelab.local"  # Change to your email
