# CoreDNS Custom Configuration
# Generated by Terraform

# Custom DNS entries
%{ for hostname, config in custom_dns_entries }
${hostname} {
    template IN ${config.type} ${hostname} {
        answer "${hostname} 60 IN ${config.type} ${config.ip}"
    }
}
%{ endfor }

# Forward to upstream DNS servers
. {
    forward . %{ for dns in upstream_dns }${dns} %{ endfor }
    cache 30
    loop
    reload
}

# Health check
health :8080

# Metrics
prometheus :9153

# Ready check
ready
