# MetalLB Configuration
# Generated by Terraform

# Controller configuration
controller:
  logLevel: ${log_level}
  
  # Resource requirements
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534
  
  # Node selector
  nodeSelector:
    kubernetes.io/os: linux
  
  # Tolerations
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Equal
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule

# Speaker configuration
speaker:
  logLevel: ${log_level}
  
  # Resource requirements
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  
  # Security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
      add:
        - NET_RAW
  
  # Node selector
  nodeSelector:
    kubernetes.io/os: linux
  
  # Tolerations
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Equal
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
  
  # FRR configuration
  frr:
    enabled: false
    
  # Member list
  memberlist:
    enabled: true
    mlBindPort: 7946

# Prometheus monitoring
%{ if prometheus_monitoring }
prometheus:
  serviceAccount: prometheus-k8s
  namespace: monitoring
  podMonitor:
    enabled: true
  prometheusRule:
    enabled: true
%{ endif }

# Pod disruption budget
pdb:
  minAvailable: 1

# Service account
serviceAccount:
  controller:
    create: true
    name: ""
    annotations: {}
  speaker:
    create: true
    name: ""
    annotations: {}

# RBAC
rbac:
  create: true

# CRDs
crds:
  validationFailurePolicy: Fail
