---
all:
  children:
    homelab:
      hosts:
        homelab-server:
          ansible_host: "{{ lookup('env', 'HOMELAB_SERVER_IP') | default('192.168.16.26') }}"
          ansible_user: "{{ lookup('env', 'HOMELAB_SSH_USER') | default('kang') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOMELAB_SSH_KEY_PATH') | default('~/.ssh/id_ed25519') }}"

          # Server configuration
          server_hostname: homelab-server
          server_timezone: "{{ timezone | default('America/New_York') }}"

          # Network configuration
          homelab_network:
            domain: homelab.local
            dev_domain: dev.homelab.local
            metallb_range: "192.168.16.200-192.168.16.220"
            gitlab_ip: "192.168.16.201"
            keycloak_ip: "192.168.16.202"
            registry_ip: "192.168.16.203"
            prometheus_ip: "192.168.16.204"
            grafana_ip: "192.168.16.205"

          # K3s configuration
          k3s_version: "v1.28.5+k3s1"
          k3s_server_args:
            - "--disable=traefik"  # We'll use nginx-ingress
            - "--disable=servicelb"  # We'll use MetalLB
            - "--flannel-backend=host-gw"

          # VM configuration (for testing)
          vm_config:
            name: homelab-test-vm
            memory: 8192  # 8GB RAM
            vcpus: 4
            disk_size: 100G
            network: default
            os_variant: ubuntu22.04

          # Deployment configuration
          deploy_components:
            - k3s
            - metallb
            - cert-manager
            - nginx-ingress
            - gitlab
            - keycloak
            - monitoring
            - backup-solutions


  vars:
    # Global variables
    ansible_python_interpreter: /usr/bin/python3

    # Deployment phase (will be overridden by command line)
    phase: vm-test

    # Component versions
    versions:
      metallb: v0.13.12
      cert_manager: v1.13.3
      nginx_ingress: v1.9.5
      gitlab: 16.8.1
      keycloak: 23.0.4
      prometheus: v2.48.1
      grafana: 10.2.3
