---
all:
  children:
    homelab:
      hosts:
        homelab-server:
          ansible_host: "{{ lookup('env', 'HOMELAB_SERVER_IP') | default('192.168.16.26') }}"
          ansible_user: "{{ lookup('env', 'HOMELAB_SSH_USER') | default('kang') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOMELAB_SSH_KEY_PATH') | default('~/.ssh/id_ed25519') }}"

          # Bastion host configuration
          bastion_host: true

          # Server configuration
          server_hostname: homelab-server
          server_timezone: "{{ timezone | default('America/New_York') }}"

          # Network configuration
          homelab_network:
            domain: "{{ lookup('env', 'HOMELAB_DOMAIN') | default('homelab.local') }}"
            dev_domain: "{{ lookup('env', 'HOMELAB_DEV_DOMAIN') | default('dev.homelab.local') }}"
            metallb_range: "{{ lookup('env', 'METALLB_IP_RANGE') | default('192.168.16.200-192.168.16.220') }}"
            gitlab_ip: "{{ lookup('env', 'GITLAB_IP') | default('192.168.16.201') }}"
            keycloak_ip: "{{ lookup('env', 'KEYCLOAK_IP') | default('192.168.16.202') }}"
            registry_ip: "{{ lookup('env', 'REGISTRY_IP') | default('192.168.16.203') }}"
            prometheus_ip: "{{ lookup('env', 'PROMETHEUS_IP') | default('192.168.16.204') }}"
            grafana_ip: "{{ lookup('env', 'GRAFANA_IP') | default('192.168.16.205') }}"

          # K3s configuration
          k3s_version: "v1.28.5+k3s1"
          k3s_server_args:
            - "--disable=traefik"  # We'll use nginx-ingress
            - "--disable=servicelb"  # We'll use MetalLB
            - "--flannel-backend=host-gw"

          # VM configuration (for testing)
          vm_config:
            name: "{{ lookup('env', 'VM_NAME') | default('homelab-test-vm') }}"
            memory: "{{ lookup('env', 'VM_MEMORY') | default('8192') | int }}"
            vcpus: "{{ lookup('env', 'VM_VCPUS') | default('4') | int }}"
            disk_size: "{{ lookup('env', 'VM_DISK_SIZE') | default('100G') }}"
            network: default
            os_variant: ubuntu22.04

          # Deployment configuration
          deploy_components:
            - k3s
            - metallb
            - cert-manager
            - nginx-ingress
            - gitlab
            - keycloak
            - monitoring
            - backup-solutions

    cluster:
      hosts:
        # VM Test Node (accessed through homelab-server)
        test-vm:
          ansible_host: "{{ vm_ip_address | default('192.168.122.100') }}"
          ansible_user: kang
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOMELAB_SSH_KEY_PATH') | default('~/.ssh/id_ed25519') }}"
          ansible_ssh_common_args: '-o ProxyJump={{ hostvars["homelab-server"]["ansible_user"] }}@{{ hostvars["homelab-server"]["ansible_host"] }} -o StrictHostKeyChecking=no'
          node_role: worker

        # Add future bare-metal nodes here following the same pattern
        # cluster-node-1:
        #   ansible_host: 192.168.16.100
        #   ansible_user: kang
        #   ansible_ssh_private_key_file: "{{ lookup('env', 'HOMELAB_SSH_KEY_PATH') | default('~/.ssh/id_ed25519') }}"
        #   ansible_ssh_common_args: '-o ProxyJump={{ hostvars["homelab-server"]["ansible_user"] }}@{{ hostvars["homelab-server"]["ansible_host"] }} -o StrictHostKeyChecking=no'
        #   node_role: master

  vars:
    # Global variables
    ansible_python_interpreter: /usr/bin/python3

    # Deployment phase (will be overridden by command line)
    phase: vm-test

    # Component versions
    versions:
      metallb: v0.13.12
      cert_manager: v1.13.3
      nginx_ingress: v1.9.5
      gitlab: 16.8.1
      keycloak: 23.0.4
      prometheus: v2.48.1
      grafana: 10.2.3
