apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
stringData:
  # OAuth2 client secret for Prometheus - MUST be set via environment variable
  client-secret: ${PROMETHEUS_OAUTH2_CLIENT_SECRET}
  # Cookie encryption secret - MUST be set via environment variable (32-byte random)
  cookie-secret: ${PROMETHEUS_OAUTH2_COOKIE_SECRET}
---
apiVersion: v1
kind: ConfigMap
