---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-oauth-secret
  namespace: oauth2-proxy
type: Opaque
stringData:
  client-secret: prometheus-client-secret
  cookie-secret: SEQzeUMxN1JmR3VYVGg4dXRHWXNLRGZLYUJ2bDhqUXM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-oauth2-proxy-config
  namespace: oauth2-proxy
data:
  oauth2_proxy.cfg: |
    # OIDC Config for Prometheus
    provider = "keycloak-oidc"
    client_id = "prometheus"
    oidc_issuer_url = "https://auth.homelab.local/realms/homelab"
    insecure_oidc_allow_unverified_email = true
    insecure_oidc_skip_issuer_verification = true
    skip_oidc_discovery = false

    # Redirect URL
    redirect_url = "https://prometheus.homelab.local/oauth2/callback"

    # Upstream and reverse proxy config
    http_address = "0.0.0.0:4180"
    reverse_proxy = true
    upstreams = ["http://prometheus.monitoring.svc.cluster.local:9090"]

    # Session and security
    cookie_secure = true
    cookie_httponly = true
    cookie_samesite = "lax"
    cookie_name = "_prometheus_oauth2_proxy"
    cookie_expire = "24h0m0s"
    cookie_refresh = "1h0m0s"
    cookie_domains = [".homelab.local"]

    # Skip auth for health checks
    skip_auth_regex = [
      "^/oauth2/",
      "^/ping$",
      "^/ready$"
    ]

    # Headers
    set_xauthrequest = true
    pass_access_token = true
    pass_user_headers = true
    pass_authorization_header = true

    # Logging
    silence_ping_logging = true
    request_logging = true

    # Allow all authenticated users
    email_domains = ["*"]

    # Role-based access
    allowed_roles = ["prometheus-admin", "prometheus-user"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-oauth2-proxy
  namespace: oauth2-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-oauth2-proxy
  template:
    metadata:
      labels:
        app: prometheus-oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
        args:
        - --config=/etc/oauth2-proxy/oauth2_proxy.cfg
        ports:
        - containerPort: 4180
          protocol: TCP
        env:
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: prometheus-oauth-secret
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: prometheus-oauth-secret
              key: cookie-secret
        volumeMounts:
        - name: config
          mountPath: /etc/oauth2-proxy
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4180
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: prometheus-oauth2-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    app: prometheus-oauth2-proxy
  ports:
  - name: http
    port: 4180
    targetPort: 4180
---
# Update Prometheus Ingress to use OAuth2 Proxy
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-https-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "homelab-ca-issuer"
    # Remove OAuth2 proxy annotations since we'll handle it directly
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prometheus.homelab.local
    secretName: prometheus-tls-cert
  rules:
  - host: prometheus.homelab.local
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: prometheus-oauth2-proxy
            namespace: oauth2-proxy
            port:
              number: 4180
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-oauth2-proxy
            namespace: oauth2-proxy
            port:
              number: 4180
