apiVersion: v2
name: CHART_NAME
description: A Helm chart for CHART_DESCRIPTION
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - homelab
  - kubernetes
  - infrastructure

home: https://github.com/your-org/homelab-infra
sources:
  - https://github.com/your-org/homelab-infra

maintainers:
  - name: Homelab Team
    email: homelab@example.com

dependencies: []
  # - name: postgresql
  #   version: "12.x.x"
  #   repository: "https://charts.bitnami.com/bitnami"
  #   condition: postgresql.enabled

annotations:
  category: Infrastructure
  licenses: MIT

  # Artifacthub annotations
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/your-org/homelab-infra/tree/main/helm/charts/CHART_NAME
    - name: Documentation
      url: https://github.com/your-org/homelab-infra/blob/main/helm/charts/CHART_NAME/README.md
  artifacthub.io/screenshots: |
    - title: Dashboard Screenshot
      url: https://example.com/screenshot.png
  artifacthub.io/changes: |
    - kind: added
      description: Initial chart version
