# GitLab Helm Values Template
# Latest stable version with recommended configurations

gitlab:
  # Image Configuration
  image:
    tag: "${GITLAB_VERSION:-16.9.1}-ee"

  # Global GitLab Configuration
  global:
    edition: ee

    # Security contexts for rootless deployment
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL

    # Hosts Configuration
    hosts:
      domain: "${HOMELAB_DOMAIN:-homelab.local}"
      externalIP: "${GITLAB_IP:-192.168.16.201}"
      ssh:
        port: 22

    # Ingress Configuration
    ingress:
      enabled: true
      class: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      tls:
        enabled: true

    # OIDC Configuration (Keycloak Integration)
    appConfig:
      omniauth:
        enabled: true
        autoSignInWithProvider: null
        syncProfileFromProvider: []
        syncProfileAttributes: ["email"]
        allowSingleSignOn: ["openid_connect"]
        blockAutoCreatedUsers: false
        autoLinkSamlUser: false
        autoLinkLdapUser: false
        providers:
          - secret: gitlab-oidc-secret # pragma: allowlist secret
            key: provider

    # SMTP Configuration
    smtp:
      enabled: false # Set to true and configure in secrets

    # Time Zone
    timeZone: "${TIMEZONE:-America/New_York}"

  # Component Configuration
  postgresql:
    install: true
    postgresqlPassword: "" # Set in secrets

  redis:
    install: true

  # GitLab Runner
  gitlab-runner:
    install: true
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    runners:
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "gitlab"
            image = "ubuntu:22.04"
            [runners.kubernetes.pod_security_context]
              run_as_non_root = true
              run_as_user = 1000
              run_as_group = 1000
              fs_group = 1000
            [[runners.kubernetes.pod_security_context.seccomp_profile]]
              type = "RuntimeDefault"

  # Registry Configuration
  registry:
    enabled: true
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    ingress:
      enabled: true
      tls:
        enabled: true

  # Monitoring
  prometheus:
    install: false # We use external Prometheus

  # Resource Configuration
  webservice:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi

  sidekiq:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  # Persistence
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "local-path"
