# Keycloak Helm Values Template
# Latest stable version with recommended configurations

keycloak:
  # Image Configuration
  image:
    tag: "${KEYCLOAK_VERSION:-24.0.1}"

  # Replica Configuration
  replicaCount: 1

  # Resource Configuration
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

  # Environment Variables
  extraEnv:
    - name: KC_PROXY
      value: "edge"
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
    - name: KC_HTTP_ENABLED
      value: "true"

  # Database Configuration
  postgresql:
    enabled: true
    auth:
      database: "keycloak"
      username: "keycloak"
      # password: set in secrets
    primary:
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

  # Service Configuration
  service:
    type: ClusterIP
    ports:
      http: 8080

  # Ingress Configuration
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    hostname: "keycloak.${HOMELAB_DEV_DOMAIN:-dev.homelab.local}"
    tls: true

  # Health Checks
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 30
    failureThreshold: 3

  # Startup Probe
  startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 30
    failureThreshold: 60

  # Persistence
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "local-path"

  # Cache Configuration
  cache:
    enabled: true

  # Metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

  # Security Context - Enhanced for rootless deployment
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false  # Keycloak needs write access
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
