# GitLab Secrets Configuration
# These should be encrypted using SOPS or sealed-secrets in production

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab
type: Opaque
stringData:
  # GitLab root password
  gitlab-root-password: "CHANGE_ME_GITLAB_ROOT_PASSWORD"

  # GitLab database credentials
  gitlab-db-username: "gitlab"
  gitlab-db-password: "CHANGE_ME_GITLAB_DB_PASSWORD"

  # GitLab shell host keys (generate with ssh-keygen)
  ssh_host_rsa_key: |
    # TEMPLATE: Generate RSA key with: ssh-keygen -t rsa -f ssh_host_rsa_key
    # Replace this comment with actual private key content

  ssh_host_ecdsa_key: |
    # TEMPLATE: Generate ECDSA key with: ssh-keygen -t ecdsa -f ssh_host_ecdsa_key
    # Replace this comment with actual private key content

  ssh_host_ed25519_key: |
    # TEMPLATE: Generate Ed25519 key with: ssh-keygen -t ed25519 -f ssh_host_ed25519_key
    # Replace this comment with actual private key content

---
# GitLab Container Registry Secrets
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secrets
  namespace: gitlab
type: Opaque
stringData:
  registry-auth-secret: "CHANGE_ME_REGISTRY_AUTH_SECRET"
  registry-s3-access-key: "CHANGE_ME_S3_ACCESS_KEY"
  registry-s3-secret-key: "CHANGE_ME_S3_SECRET_KEY"

---
# GitLab Redis Secret
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis-secret
  namespace: gitlab
type: Opaque
stringData:
  redis-password: "CHANGE_ME_REDIS_PASSWORD"
