# Keycloak Secrets Configuration
# These should be encrypted using SOPS or sealed-secrets in production

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  # Keycloak admin credentials
  admin-username: "admin"
  admin-password: "CHANGE_ME_KEYCLOAK_ADMIN_PASSWORD"

  # Keycloak database credentials
  db-username: "keycloak"
  db-password: "CHANGE_ME_KEYCLOAK_DB_PASSWORD"

  # Management user for health checks
  management-username: "management"
  management-password: "CHANGE_ME_MANAGEMENT_PASSWORD"

---
# Keycloak Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  username: "keycloak"
  password: "CHANGE_ME_KEYCLOAK_DB_PASSWORD"
  database: "keycloak"
  host: "keycloak-postgres"
  port: "5432"

---
# Keycloak TLS Secret (for client certificates)
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls-secret
  namespace: keycloak
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  tls.crt: |
    # BASE64_ENCODED_CERTIFICATE
  tls.key: |
    # BASE64_ENCODED_PRIVATE_KEY
