apiVersion: v2
name: core-infrastructure
description: Core infrastructure components for homelab k3s cluster
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: metallb
    version: "0.14.8"
    repository: https://metallb.github.io/metallb
    condition: metallb.enabled

  - name: cert-manager
    version: "v1.15.3"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

  - name: ingress-nginx
    version: "4.11.2"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

  - name: sealed-secrets
    version: "2.16.1"
    repository: https://bitnami-labs.github.io/sealed-secrets
    condition: sealed-secrets.enabled

maintainers:
  - name: homelab-admin
    email: admin@homelab.local
