# Unified Domain Configuration
# Single source of truth for all domain-related settings
# Consolidated from config/base/global.yaml and config/base/domains.yaml

domains:
  base:
    primary: "homelab.local"
    tld: "local"

# Global settings (from global.yaml)
global:
  domain:
    base: "homelab.local"
    tld: "local"

  # Common Labels
  labels:
    app.kubernetes.io/managed-by: "homelab-infra"
    app.kubernetes.io/part-of: "homelab"
    homelab.local/environment: "{{ .Values.environment }}"
    homelab.local/component: "{{ .Values.component }}"

  # Service subdomains - automatically generate URLs
  services:
    auth: "auth.homelab.local"
    homelab: "homelab.local"
    grafana: "grafana.homelab.local"
    prometheus: "prometheus.homelab.local"
    ollama: "ollama.homelab.local"
    jupyter: "jupyter.homelab.local"
    gitlab: "gitlab.homelab.local"
    keycloak: "keycloak.homelab.local"

  # Environment-specific overrides
  environments:
    development:
      suffix: "dev"
      base: "dev.homelab.local"
    staging:
      suffix: "staging"
      base: "staging.homelab.local"
    production:
      suffix: ""
      base: "homelab.local"

# DNS Configuration
dns:
  cluster_dns: "10.43.0.10"
  search_domains:
    - "homelab.local"
    - "svc.cluster.local"
    - "cluster.local"

# Certificate Management
# Certificate Management (consolidated)
certificates:
  issuer:
    email: "admin@homelab.local"
    staging_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    production_server: "https://acme-v02.api.letsencrypt.org/directory"

  defaults:
    duration: "2160h" # 90 days
    renewBefore: "360h" # 15 days
    algorithm: "RSA"
    size: 2048

  ca:
    common_name: "Homelab CA"
    organization: "Homelab"
    organizational_unit: "Homelab Infrastructure"
    country: "US"
    province: "Home"
    locality: "Lab"

# Image Registry Settings (from global.yaml)
registry:
  default: "docker.io"
  pullPolicy: "IfNotPresent"
  pullSecrets: []

# Common Annotations
annotations:
  deployment.kubernetes.io/revision: '{{ .Values.revision | default "1" }}'
  homelab.local/managed-by: "centralized-config"
  homelab.local/last-updated: '{{ now | date "2006-01-02T15:04:05Z" }}'
