---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = grafana.homelab.local
    root_url = https://grafana.homelab.local
    serve_from_sub_path = false

    [security]
    admin_user = admin
    admin_password = admin
    allow_embedding = true

    [auth]
    disable_login_form = false
    disable_signout_menu = false

    [auth.generic_oauth]
    enabled = true
    name = Keycloak SSO
    allow_sign_up = true
    client_id = homelab-portal
    client_secret = homelab-portal-secret
    scopes = openid profile email
    empty_scopes = false
    auth_url = https://auth.homelab.local/realms/homelab/protocol/openid-connect/auth
    token_url = https://auth.homelab.local/realms/homelab/protocol/openid-connect/token
    api_url = https://auth.homelab.local/realms/homelab/protocol/openid-connect/userinfo
    login_attribute_path = preferred_username
    groups_attribute_path = groups
    name_attribute_path = name
    email_attribute_path = email
    role_attribute_path = contains(groups[*], 'admin') && 'Admin' || 'Viewer'
    auto_login = false
    use_pkce = true

    [users]
    allow_sign_up = true
    auto_assign_org = true
    auto_assign_org_id = 1
    auto_assign_org_role = Viewer

    [log]
    mode = console
    level = info
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.1.3
        ports:
        - containerPort: 3000
        env:
        - name: GF_PATHS_CONFIG
          value: /etc/grafana/grafana.ini
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-config
          mountPath: /etc/grafana
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-data
      - name: grafana-config
        configMap:
          name: grafana-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-https-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "homelab-ca-issuer"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - grafana.homelab.local
    secretName: grafana-tls-cert
  rules:
  - host: grafana.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-cert
  namespace: monitoring
spec:
  secretName: grafana-tls-cert
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  commonName: grafana.homelab.local
  dnsNames:
  - grafana.homelab.local
