apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
data:
  # Client secret - MUST be set via environment variable or external secret management
  client-secret: ${OAUTH2_CLIENT_SECRET}
  # Cookie encryption secret - MUST be set via environment variable (32-byte random)
  cookie-secret: ${OAUTH2_COOKIE_SECRET}
---
apiVersion: v1
kind: ConfigMap
