---
# cert-manager Deployment
# Deploys cert-manager for automatic SSL certificate management

- name: Deploy cert-manager
  debug:
    msg: "🔒 Deploying cert-manager for SSL certificates..."

- name: Install cert-manager
  shell: |
    # Add cert-manager Helm repository
    helm repo add jetstack https://charts.jetstack.io
    helm repo update

    # Install cert-manager
    helm upgrade --install cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --create-namespace \
      --version {{ versions.cert_manager }} \
      --set installCRDs=true \
      --wait
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Display cert-manager status
  debug:
    msg: "✅ cert-manager deployed successfully!"
