---
# Test Bastion Host Access Pattern
# Verifies that cluster nodes can be accessed through the homelab server

- name: Test bastion host access pattern
  hosts: cluster
  gather_facts: false
  tasks:
    - name: Test basic connectivity through bastion
      ping:
      register: ping_result

    - name: Get basic system information through bastion
      shell: |
        echo "=== System Info via Bastion ==="
        echo "Hostname: $(hostname)"
        echo "IP Address: $(hostname -I | awk '{print $1}')"
        echo "Uptime: $(uptime -p)"
        echo "SSH connection through bastion successful!"
      register: system_info

    - name: Display connection results
      debug:
        msg:
          - "✅ Bastion access successful for {{ inventory_hostname }}"
          - "Connection: {{ ansible_host }} via {{ hostvars['homelab-server']['ansible_host'] }}"
          - "System info: {{ system_info.stdout_lines }}"

- name: Test direct homelab server access
  hosts: homelab-server
  gather_facts: false
  tasks:
    - name: Verify homelab server is accessible
      ping:

    - name: Show bastion host information
      debug:
        msg:
          - "🏠 Homelab Server (Bastion Host)"
          - "IP: {{ ansible_host }}"
          - "User: {{ ansible_user }}"
          - "This server provides secure access to all cluster nodes"
