{{- if .Values.helmReleaseMonitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-helm-releases
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    component: helm-release-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-release-monitor
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-helm-release-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    component: helm-release-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-release-monitor
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helm-release-monitor
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "monitoring.fullname" . }}-helm-release-monitor
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      containers:
      - name: helm-release-monitor
        image: "{{ .Values.helmReleaseMonitoring.image.repository }}:{{ .Values.helmReleaseMonitoring.image.tag }}"
        imagePullPolicy: {{ .Values.helmReleaseMonitoring.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        env:
        - name: PROMETHEUS_PORT
          value: "8080"
        - name: CHECK_INTERVAL
          value: "{{ .Values.helmReleaseMonitoring.checkInterval }}"
        - name: NAMESPACE_SELECTOR
          value: "{{ .Values.helmReleaseMonitoring.namespaceSelector }}"
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.helmReleaseMonitoring.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.global.securityContext | nindent 12 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring.fullname" . }}-helm-release-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    component: helm-release-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "monitoring.fullname" . }}-helm-release-monitor
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    component: helm-release-monitor
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "monitoring.fullname" . }}-helm-release-monitor
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    component: helm-release-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "monitoring.fullname" . }}-helm-release-monitor
subjects:
- kind: ServiceAccount
  name: {{ include "monitoring.fullname" . }}-helm-release-monitor
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-helm-release-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/name: helm-release-monitor
    component: helm-release-monitor
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: helm-release-monitor
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
{{- end }}
