apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../applications/infrastructure.yaml
  - ../../applications/monitoring.yaml
  - certificates.yaml
  - metallb-config.yaml

patchesStrategicMerge:
  - patches/metallb-dev.yaml
  - patches/monitoring-dev.yaml
  - patches/resources-dev.yaml

commonLabels:
  environment: development
  managed-by: gitops

commonAnnotations:
  deployment.kubernetes.io/environment: development
  gitops.argoproj.io/sync-options: CreateNamespace=true
