apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: development-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.25.200-192.168.25.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: development-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - development-pool
