apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: development-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.16.100-192.168.16.110
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: development-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - development-pool
