repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: longhorn
    url: https://charts.longhorn.io
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

environments:
  development:
    values:
      - environments/values-dev.yaml
  staging:
    values:
      - environments/values-staging.yaml
  production:
    values:
      - environments/values-prod.yaml

releases:
  # Core Infrastructure - Deploy First
  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    version: "0.14.8"
    values:
      - charts/core-infrastructure/values.yaml
      - charts/core-infrastructure/values-{{ .Environment.Name }}.yaml
    set:
      - name: controller.resources.limits.cpu
        value: "100m"
      - name: controller.resources.limits.memory
        value: "100Mi"
    wait: true
    timeout: 300

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: "v1.15.3"
    values:
      - charts/core-infrastructure/values.yaml
      - charts/core-infrastructure/values-{{ .Environment.Name }}.yaml
    set:
      - name: installCRDs
        value: true
    wait: true
    timeout: 300
    needs:
      - metallb

  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: "4.11.2"
    values:
      - charts/core-infrastructure/values.yaml
      - charts/core-infrastructure/values-{{ .Environment.Name }}.yaml
    wait: true
    timeout: 300
    needs:
      - metallb
      - cert-manager

  - name: sealed-secrets
    namespace: kube-system
    chart: sealed-secrets/sealed-secrets
    version: "2.16.1"
    values:
      - charts/core-infrastructure/values.yaml
      - charts/core-infrastructure/values-{{ .Environment.Name }}.yaml
    wait: true
    timeout: 300

  # Storage - Deploy Second
  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    version: "1.7.1"
    values:
      - charts/storage/values.yaml
      - charts/storage/values-{{ .Environment.Name }}.yaml
    wait: true
    timeout: 600
    needs:
      - ingress-nginx

  # Monitoring Stack - Deploy Last
  - name: kube-prometheus-stack
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: "61.7.2"
    values:
      - charts/monitoring/values.yaml
      - charts/monitoring/values-{{ .Environment.Name }}.yaml
    wait: true
    timeout: 600
    needs:
      - longhorn
      - ingress-nginx

  - name: loki
    namespace: monitoring
    chart: grafana/loki
    version: "6.6.4"
    values:
      - charts/monitoring/values.yaml
      - charts/monitoring/values-{{ .Environment.Name }}.yaml
    wait: true
    timeout: 300
    needs:
      - longhorn

  - name: promtail
    namespace: monitoring
    chart: grafana/promtail
    version: "6.16.4"
    values:
      - charts/monitoring/values.yaml
      - charts/monitoring/values-{{ .Environment.Name }}.yaml
    wait: true
    timeout: 300
    needs:
      - loki

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: "8.4.2"
    values:
      - charts/monitoring/values.yaml
      - charts/monitoring/values-{{ .Environment.Name }}.yaml
    wait: true
    timeout: 300
    needs:
      - kube-prometheus-stack
      - loki
