apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tzervas/homelab-infra.git
    targetRevision: HEAD
    path: deployments/gitops/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
spec:
  description: Homelab Infrastructure Project
  sourceRepos:
    - 'https://github.com/tzervas/homelab-infra.git'
    - 'git@github.com:tzervas/homelab-infra-private.git'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://charts.jetstack.io'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://charts.longhorn.io'
    - 'https://argoproj.github.io/argo-helm'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingAdmissionWebhook
    - group: 'admissionregistration.k8s.io'
      kind: MutatingAdmissionWebhook
    - group: 'networking.k8s.io'
      kind: IngressClass
    - group: 'policy'
      kind: PodSecurityPolicy
    - group: 'security.istio.io'
      kind: PeerAuthentication
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'extensions'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'policy'
      kind: '*'
    - group: 'cert-manager.io'
      kind: '*'
    - group: 'monitoring.coreos.com'
      kind: '*'
    - group: 'longhorn.io'
      kind: '*'
  roles:
    - name: homelab-admin
      description: Admin access to homelab project
      policies:
        - p, proj:homelab:homelab-admin, applications, *, homelab/*, allow
        - p, proj:homelab:homelab-admin, repositories, *, homelab/*, allow
        - p, proj:homelab:homelab-admin, clusters, *, *, allow
      groups:
        - homelab-admins
    - name: homelab-developer
      description: Developer access to homelab project
      policies:
        - p, proj:homelab:homelab-developer, applications, get, homelab/*, allow
        - p, proj:homelab:homelab-developer, applications, sync, homelab/*, allow
        - p, proj:homelab:homelab-developer, repositories, get, homelab/*, allow
      groups:
        - homelab-developers
