apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.6
    helm:
      parameters:
        - name: global.domain
          value: argocd.homelab.local
        - name: server.ingress.enabled
          value: "true"
        - name: server.ingress.ingressClassName
          value: nginx
        - name: server.ingress.hosts[0]
          value: argocd.homelab.local
        - name: server.ingress.tls[0].secretName
          value: argocd-server-tls
        - name: server.ingress.tls[0].hosts[0]
          value: argocd.homelab.local
        - name: server.config.url
          value: https://argocd.homelab.local
        - name: server.config.oidc.config
          value: |
            name: Keycloak
            issuer: https://keycloak.homelab.local/realms/homelab
            clientId: argocd
            clientSecret: $oidc.keycloak.clientSecret
            requestedScopes: ["openid", "profile", "email", "groups"]
            requestedIDTokenClaims: {"groups": {"essential": true}}
        - name: configs.secret.argocdServerAdminPassword
          value: "$2a$12$placeholder.replace.with.bcrypt.hash"
        - name: reposerver.rbac.create
          value: "true"
        - name: server.rbac.create
          value: "true"
        - name: controller.rbac.create
          value: "true"
      values: |
        global:
          domain: argocd.homelab.local
        configs:
          repositories:
            homelab-infra:
              url: https://github.com/tzervas/homelab-infra.git
              type: git
            homelab-infra-private:
              url: git@github.com:tzervas/homelab-infra-private.git
              type: git
              sshPrivateKeySecret:
                name: private-repo-secret
                key: sshPrivateKey
        server:
          extraArgs:
            - --insecure
          config:
            repositories: |
              - type: git
                url: https://github.com/tzervas/homelab-infra.git
              - type: git
                url: git@github.com:tzervas/homelab-infra-private.git
                sshPrivateKeySecret:
                  name: private-repo-secret
                  key: sshPrivateKey
            policy.default: role:readonly
            policy.csv: |
              p, role:admin, applications, *, */*, allow
              p, role:admin, clusters, *, *, allow
              p, role:admin, repositories, *, *, allow
              g, argocd-admins, role:admin
        dex:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    app.kubernetes.io/managed-by: argocd
