apiVersion: v1
kind: Secret
metadata:
  name: homelab-infra-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/tzervas/homelab-infra.git
  name: homelab-infra
---
apiVersion: v1
kind: Secret
metadata:
  name: homelab-infra-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:tzervas/homelab-infra-private.git
  name: homelab-infra-private
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Replace with actual SSH private key for private repository access
    # Generate with: ssh-keygen -t ed25519 -C "argocd@homelab"
    # Add public key to repository deploy keys
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-repositories
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: bitnami
  url: https://charts.bitnami.com/bitnami
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-community-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: jetstack-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: jetstack
  url: https://charts.jetstack.io
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: longhorn
  url: https://charts.longhorn.io
