name: Security Scans

on:
  pull_request:
  push:
    branches:
      - main
      - "feat/**"
      - "feature/**"
  workflow_dispatch:

jobs:
  repository-scan:
    name: Repository Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Check repository health
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          python scripts/monitoring/repo_health_check.py

      - name: Check for large files
        run: |
          # Check for large files, excluding .git and other ignored directories
          result=$(find . -type d \( -name .git -o -name node_modules -o -name .terraform \) -prune -o -type f -size +50M -print)
          if [ -n "$result" ]; then
            echo "⚠️ Large files found:"
            echo "$result"
            exit 1
          fi

  secret-scan:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog-actions-scan@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  vulnerability-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          security-checks: "vuln,config,secret"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
